# Generated by Django 6.1.1 on 2026-09-12 09:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('SNACK', 'Snack'), ('DRINK', 'Drink'), ('DESSERT', 'Dessert')], max_length=20, null=True)),
                ('ingredients', models.TextField(blank=True, null=True)),
                ('diet_type', models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], max_length=20, null=True)),
                ('spice_level', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('SPICY', 'Spicy')], max_length=20, null=True)),
                ('preparation_time', models.IntegerField(help_text='Preparation time in minutes')),
                ('calories', models.IntegerField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('preferences', models.JSONField(default=dict)),
                ('recommendations', models.JSONField(default=list)),
                ('selected_recommendation', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_history', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diet_type', models.CharField(blank=True, choices=[('VEG', 'Vegetarian'), ('NON_VEG', 'Non-Vegetarian'), ('VEGAN', 'Vegan')], max_length=20, null=True)),
                ('min_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('max_budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('spice_preference', models.CharField(blank=True, choices=[('MILD', 'Mild'), ('MEDIUM', 'Medium'), ('SPICY', 'Spicy')], max_length=20, null=True)),
                ('max_preparation_time', models.IntegerField(blank=True, help_text='In minutes', null=True)),
                ('favorite_categories', models.JSONField(blank=True, default=list)),
                ('favorite_foods', models.JSONField(blank=True, default=list)),
                ('allergies', models.JSONField(blank=True, default=list)),
                ('foods_to_avoid', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='api.fooditem')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'food'), name='unique_user_food_favorite')],
            },
        ),
    ]
